### ISSUE TITLE
EntitySet KeyNames clash with other applications

### ISSUE THREAD

**Issue by nak2000** [silentbobbert/EFCache.Redis#18]
The keys for the entityset names, have a preset Prefix "__EFCache.Redis_EntitySetKey_"
this is ok so long as the SetName's dont clash between applications, we have multiple apps using the same redis cluster, and happen to have the same entityset name.
which is causing one to overwrite the other.

can you add support so that it uses the EntitySetName, and the name of the DbContext class or the clientname from the redis connection string, or a way to set the prefix in RedisCache Class

**Comment by tiwariarvin** [comment]
@nak2000: This is not supported as of now, though nice to have. This will help reduce cost for Staging and Development environments and also for small applications.

@silentbobbert: I can do this probably by the end of this month as It will potentially reduce cost for @nak2000, me and other who are willing to do so. Thoughts?

**Comment by silentbobbert** [comment]
@tiwariarvin I think the idea has merit and as an extensibility point, it would add value. For some people the current behaviour is correct - because it does represent the same entity across application boundaries, changes to them are reflected everywhere. For some like @nak2000 its a name clash where the entities are different and should remain so.

Making this configurable would satisfy both use cases, but I wont have time to do this for quite some time. As always, I am happy to accept pull requests! :+1:

**Comment by tiwariarvin** [comment]
I did't had time to address this until now. Possibly, should be able to get this done by mid May.

I won't mind if anyone else want to implement the same.

**Comment by tiwariarvin** [comment]
@silentbobbert Resolved under pull request #20 

@nak2000, please realize that -
1. All entity keys implicitly prefixed with "DB name" by Entity Framework and therefore don't need any extra work to help them differentiate between two or more databases,
2. The **"cache qualifier" added to an overloaded constructor** will only be prefixed to "entity set" name created by this library so that it can be differentiated when intended. For example, if you are intended to share a "Redis" DB between two databases then the "cache qualifier" should be set to respective "database name". Below is the sample use -

`//init EFCache.Redis.RedisCache with cache identifier set to database name
cache = new RedisCache(RedisHelper.GetRedisConnectionString(), databaseName);`

**Comment by silentbobbert** [comment]
Pull Request merged. NuGet packaged published. Issue fixed in version 2016.5.2.1
