### ISSUE TITLE
 Spatial readers can only be produced from readers of type SqlDataReader

### ISSUE THREAD

**Issue by zumicts** [silentbobbert/EFCache.Redis#19]
Exception thrown: 'System.Data.Entity.Core.ProviderIncompatibleException' in EntityFramework.SqlServer.dll

    Additional information: Spatial readers can only be produced from readers of type SqlDataReader. A reader of type EFCache.CachingReader was provided.

**Comment by silentbobbert** [comment]
Hey @zumicts - can you provide any information about your setup and use case? Is this limited to certain operations or all of them?

Is it only occurring when using spatial data types for instance?

I have never personally had cause to use spatial data types, so any information you can provide to help reproduce the error  would be of great value.

As it stands, I will not be able to address the problem you reported.

**Comment by silentbobbert** [comment]
@zumicts I have researched this issue and believe the problem comes from EFCache.CachingProviderServices, which is not under the control of this project. Please see http://efcache.codeplex.com/ to report your issue there.

This Redis cache project adds a redis implementation of ICache instead of the "In-Memory" cache, but both are dependant on CachingProviderServices

I googled the error message you gave me and found this page:
http://www.getcodesamples.com/src/F22E9B4/B1F82F0A

It seems that the implementation somewhere deeper than my project is being specific about the type of DataReader required.

There is nothing I can do.

**Comment by zumicts** [comment]
You're right. I'll fork it and try to fix that. That files seems to help with the search for the bug. Thanks
