### ISSUE TITLE
there is something wrong with you code (performance)

### ISSUE THREAD

**Issue by qinshimignyue** [silentbobbert/EFCache.Redis#29]
1.first you create ConnectionMultiplexer   every time
2.you lock every method that use _database

first ConnectionMultiplexer  is thread safe.
second _redis.GetDatabase() return a new object....

do you think that I am right?
=================================
The central object in StackExchange.Redis is the ConnectionMultiplexer class in the StackExchange.Redis namespace; this is the object that hides away the details of multiple servers. Because the ConnectionMultiplexer does a lot, it is designed to beshared and reused between callers. You should not create a ConnectionMultiplexer per operation. It is fully thread-safe and ready for this usage. In all the subsequent examples it will be assumed that you have a ConnectionMultiplexer instance stored away for re-use. But for now, let's create one. This is done using ConnectionMultiplexer.Connect orConnectionMultiplexer.ConnectAsync, passing in either a configuration string or a ConfigurationOptions object. The configuration string can take the form of a comma-delimited series of nodes, so let's just connect to an instance on the local machine on the default port (6379):

https://github.com/StackExchange/StackExchange.Redis/blob/master/Docs/Basics.md
​

**Comment by nguyendangdung** [comment]
1.first you create ConnectionMultiplexer every time

I dont see he was doing this

**Comment by silentbobbert** [comment]
This method sets up the connection:

_redis = ConnectionMultiplexer.Connect(options);

And it is called in the constructor of RedisCache so only called once.

It is threadsafe, so it might be possible to register an instance of same object within your IoC container as a singleton.

It might be possible to provide another constructor that takes the object in via DI instead and feed it in from IoC.

If you reference the source version of this package instead of the nuget package, how many times do you see the _redis object get set via the existing constructors with your debugger?

**Comment by howdandy** [comment]
I can confirm that in our production instances the number of Redis connections from the EFCache.Redis provider steadily increases until the Redis server cannot deliver anymore new connections.

This issue is well defined here -> https://gavinb.net/2015/07/11/dont-get-burned-by-redis-connectionmultiplexer-a-sample-wrapper/

We estimate that we'll be forking and submitting a pull request within the next 2 weeks. We are also implementing a transient fault retry strategy. We will try to use the CachingFailed event to that end.

**Comment by silentbobbert** [comment]
No discussion on this issue for a long time. Please re-open a new issue, or better yet, submit a PR if this is still a problem.
