### ISSUE TITLE
Update to use version 2 of StackExchange

### ISSUE THREAD

**Issue by thomhubers** [silentbobbert/EFCache.Redis#37]
Current EFCache.Redis uses `StackExchange.Redis (>= 1.2.6)`

StackExchange.Redis recently got a [major update](https://stackexchange.github.io/StackExchange.Redis/ReleaseNotes) (>=2.0.495) with several long awaited improvements. 

This version has some breaking changes, and therefore EFCache.Redis is incompatible with this new version.

Is it possible to update EFCache.Redis to benefit from this updated dependency? I am open to contribute to this, but I like some ideas, coordination and supervision of the package author.

EDIT
On the other hand, I just updated the package in a separate [branch](https://github.com/WebstudioThomHubers/EFCache.Redis/tree/redis2) and all test ran successfully. I'm still interested in @silentbobbert and @geirsagberg ideas on this redis v2 update.

**Comment by thomasvdb** [comment]
Any update on this?
Updating to version 2 of StackExchange.Redis seems to be quite straightforward and would make updating our solution much easier instead of creating our own NuGet package.

**Comment by silentbobbert** [comment]
Hi @thomhubers and @thomasvdb - I have not updated my package due to the breaking changes. If any consumers of EFCache.Redis also use StackExchange.Redis independently, they could have breaking changes in their applications to deal with if I force them to use a later version with breaking changes in it. Im worried that I'll get a ton of issues reported for the breaking changes.

I had a look at [branch](https://github.com/WebstudioThomHubers/EFCache.Redis/tree/redis2) linked by @thomhubers, but I only saw config updates, and not code changes to fix the breaking changes. This would have given me a hint about how big the problems might be for consumers. I have not personally looked into the new version of StackExchange.Redis yet, or seen what the breaking changes are.

**Comment by thomasvdb** [comment]
Hi @silentbobbert,

I did not encounter any breaking changes when upgrading to v2.
https://github.com/thomasvdb/EFCache.Redis

I've updated our project with this modified version and for now everything seems to keep working.
It still needs to go through our testing phase so I will keep you in the loop.

If you create a v2 of your own library, it will indicate their will be breaking changes and consumers of your library will be aware of this I assume? Isn't that the purpose of semantic versioning?

However, I don't have any experience as a library developer so maybe I'm missing some points :)

**Comment by silentbobbert** [comment]
I have updated the library to use the new StackExchange v2 dependency. I did not encounter any breaking changes, so they must be in APIs I am not using.

Consumers of my package could have hard dependencies on the previous version 1.2.6.

Hopefully I will not receive issues, but if I do, I could produce two different packages, or roll back to 1.2.6
